#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py compilemessages
python manage.py compilejsi18n
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
