volumes:
  offgridplanner_local_postgres_data: {}
  offgridplanner_local_postgres_data_backups: {}
  offgridplanner_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: offgridplanner_local_django
    container_name: offgridplanner_local_django
    depends_on:
      - postgres
#      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: offgridplanner_production_postgres
    container_name: offgridplanner_local_postgres
    volumes:
      - offgridplanner_local_postgres_data:/var/lib/postgresql/data
      - offgridplanner_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: offgridplanner_local_mailpit
    ports:
      - "8025:8025"

# TODO enable again if being used later - currently not needed
#  redis:
#    image: docker.io/redis:6
#    container_name: offgridplanner_local_redis
#
#    volumes:
#      - offgridplanner_local_redis_data:/data


#  celeryworker:
#    <<: *django
#    image: offgridplanner_local_celeryworker
#    container_name: offgridplanner_local_celeryworker
#    depends_on:
#      - redis
#      - postgres
#      - mailpit
#    ports: []
#    command: /start-celeryworker

#  celerybeat:
#    <<: *django
#    image: offgridplanner_local_celerybeat
#    container_name: offgridplanner_local_celerybeat
#    depends_on:
#      - redis
#      - postgres
#      - mailpit
#    ports: []
#    command: /start-celerybeat

#  flower:
#    <<: *django
#    image: offgridplanner_local_flower
#    container_name: offgridplanner_local_flower
#    ports:
#      - '5555:5555'
#    command: /start-flower
