# Generated by Django 5.2.5 on 2025-09-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0006_alter_customdemand_high_alter_customdemand_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdemand',
            name='settlement_type',
            field=models.CharField(choices=[('peri-urban', 'Rural peri-urban'), ('isolated', 'Rural isolated')], default='isolated', max_length=80),
        ),
    ]
