# Generated by Django 5.2.5 on 2025-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0007_customdemand_settlement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdemand',
            name='settlement_type',
            field=models.CharField(choices=[('periurban', 'Rural peri-urban'), ('isolated', 'Rural isolated')], default='isolated', max_length=80),
        ),
    ]
