# Generated by Django 5.1.8 on 2025-11-18 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0008_alter_results_cost_grid_alter_results_cost_shs_and_more'),
        ('projects', '0009_alter_project_country_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
