# Generated by Django 5.1.8 on 2025-08-21 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_description_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='latitude_max',
            field=models.FloatField(default=13.9, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='options',
            name='latitude_min',
            field=models.FloatField(default=4.2, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='options',
            name='long_max',
            field=models.FloatField(default=14.7, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AddField(
            model_name='options',
            name='longitude_min',
            field=models.FloatField(default=2.7, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
