# Generated by Django 5.1.8 on 2025-04-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_description_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('monitoring', 'Monitoring'), ('analyzing', 'Analyzing'), ('potential', 'Potential')], default='potential', max_length=20),
        ),
    ]
