# Generated by Django 5.1.8 on 2025-04-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('monitoring', 'Monitoring'), ('analyzing', 'Analyzing')], default='analyzing', max_length=20),
        ),
    ]
