# Generated by Django 5.1.8 on 2025-08-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_options_latitude_max_options_latitude_min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='long_max',
            new_name='longitude_max',
        ),
    ]
