# Generated by Django 5.1.8 on 2025-04-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapTestSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('building_count', models.PositiveSmallIntegerField()),
                ('grid_dist', models.FloatField()),
            ],
        ),
    ]
