# Generated by Django 5.2.1 on 2025-08-19 13:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteExploration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_count_min', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(31), django.core.validators.MaxValueValidator(500)])),
                ('diameter_max', models.FloatField(default=500, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10000)])),
                ('distance_from_grid_min', models.FloatField(default=60000, validators=[django.core.validators.MinValueValidator(20000), django.core.validators.MaxValueValidator(120000)])),
                ('match_distance_max', models.FloatField(default=5000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(20000)])),
                ('latest_exploration_results', models.JSONField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exploration_id', models.TextField(null=True)),
            ],
        ),
    ]
