# Generated by Django 5.1.8 on 2025-04-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_maptestsite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maptestsite',
            unique_together={('latitude', 'longitude')},
        ),
    ]
