# Generated by Django 5.2.5 on 2025-10-07 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='siteexploration',
            name='exploration_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
